linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocyclo
    - gosec
    - prealloc
    - noctx
    - bodyclose

linters-settings:
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
    ignore-words:
      - cancelled

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
