version: 2
project_name: timeslot

builds:
  - id: timeslot
    main: ./cmd/timeslot
    binary: timeslot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]

checksum:
  name_template: checksums.txt

release:
  prerelease: auto

changelog:
  use: git
