project_name: timeslot

builds:
  - id: timeslot
    main: ./
    binary: timeslot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git
